quarkus.application.name=dog-checker-api
quarkus.http.port=8080

# Disable Dev Services for Artemis, since we want to connect to the same broker as the worker
quarkus.artemis.devservices.enabled=false

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=dogchecker
quarkus.datasource.password=dogchecker
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/dogchecker
# Automatically create/update the database schema
quarkus.hibernate-orm.database.generation=update

# AMQP
amqp-host=localhost
amqp-port=5672
amqp-username=artemis
amqp-password=artemis

# Messaging channels
mp.messaging.outgoing.check-request.connector=smallrye-amqp
mp.messaging.outgoing.check-request.address=check-request
mp.messaging.outgoing.check-request.content-type=application/json

mp.messaging.incoming.check-response.connector=smallrye-amqp
mp.messaging.incoming.check-response.address=check-response
mp.messaging.incoming.check-response.content-type=application/json
