quarkus.application.name=dog-checker-worker
quarkus.http.port=8081

# AMQP
amqp-host=localhost
amqp-port=5672
amqp-username=artemis
amqp-password=artemis

# Messaging channels
mp.messaging.incoming.check-request.connector=smallrye-amqp
mp.messaging.incoming.check-request.address=check-request
mp.messaging.incoming.check-request.content-type=application/json

mp.messaging.outgoing.check-response.connector=smallrye-amqp
mp.messaging.outgoing.check-response.address=check-response
mp.messaging.outgoing.check-response.content-type=application/json

# External APIs
dogs.api.base-url=https://api.api-ninjas.com
dogs.api.key=YOUR_API_NINJAS_KEY

weather.api.base-url=https://api.weatherapi.com
weather.api.key=YOUR_WEATHER_API_KEY

# REST Client
quarkus.rest-client.dogs-api.url=${dogs.api.base-url}
quarkus.rest-client.weather-api.url=${weather.api.base-url}
